module.exports={
    deleteComment:  require('./queryFunctions/deleteComment'),
    getBlogFooter:  require('./queryFunctions/getBlogFooter'),
    getDefinitionByPagemodule:require('./queryFunctions/getDefinitionByPagemodule'),
    getPagemodules:require('./queryFunctions/getPagemodules'),
    getPagemodules0:require('./queryFunctions/getPagemodules0'),
    getSuggestedPages:require('./queryFunctions/getSuggestedPages'),
    getSuggestedTags:require('./queryFunctions/getSuggestedTags'),
    getTags:require('./queryFunctions/getTags'),
    getTagsWithCount:require('./queryFunctions/getTagsWithCount'),
    newComment:require('./queryFunctions/newComment'),
    removePage:require('./queryFunctions/removePage'),
    editpage:require('./queryFunctions/editpage'),
    getComment:require('./queryFunctions/getComment'),
    getPage:require('./queryFunctions/getPage'),
    getPagemoduleInfo:require('./queryFunctions/getPagemoduleInfo'),
    getPagesByTags:require('./queryFunctions/getPagesByTags'),
    getPageversion:require('./queryFunctions/getPageversion'),
}
