module.exports={
    blog_getData:           require('./queryFunctions/getData'),
    blog_setData:           require('./queryFunctions/setData'),
    blog_deleteComment:     require('./queryFunctions/deleteComment'),
    blog_getDefinitionByPagemodule:
        require('./queryFunctions/getDefinitionByPagemodule'),
    blog_getPagemodules:    require('./queryFunctions/getPagemodules'),
    blog_getPagemodules0:   require('./queryFunctions/getPagemodules0'),
    getSuggestedPages:      require('./queryFunctions/getSuggestedPages'),
    getSuggestedTags:       require('./queryFunctions/getSuggestedTags'),
    getTags:                require('./queryFunctions/getTags'),
    getTagsWithCount:       require('./queryFunctions/getTagsWithCount'),
    newComment:             require('./queryFunctions/newComment'),
    removePage:             require('./queryFunctions/removePage'),
    editpage:               require('./queryFunctions/editpage'),
    getComment:             require('./queryFunctions/getComment'),
    getPage:                require('./queryFunctions/getPage'),
    getPagemoduleInfo:      require('./queryFunctions/getPagemoduleInfo'),
    getPagesByTags:         require('./queryFunctions/getPagesByTags'),
    getPageversion:         require('./queryFunctions/getPageversion'),
}
