module.exports={
    blog_deleteComment:     require('./queryFunctions/deleteComment'),
    blog_editpage:          require('./queryFunctions/editpage'),
    blog_getComment:        require('./queryFunctions/getComment'),
    blog_getData:           require('./queryFunctions/getData'),
    blog_getDefinitionByPagemodule:
        require('./queryFunctions/getDefinitionByPagemodule'),
    blog_getPagemodules:    require('./queryFunctions/getPagemodules'),
    blog_getPagemodules0:   require('./queryFunctions/getPagemodules0'),
    blog_getSuggestedPages: require('./queryFunctions/getSuggestedPages'),
    blog_getSuggestedTags:  require('./queryFunctions/getSuggestedTags'),
    blog_getTags:           require('./queryFunctions/getTags'),
    blog_getTagsWithCount:  require('./queryFunctions/getTagsWithCount'),
    blog_getPage:           require('./queryFunctions/getPage'),
    blog_getPagemoduleInfo: require('./queryFunctions/getPagemoduleInfo'),
    blog_getPagesByTags:    require('./queryFunctions/getPagesByTags'),
    blog_getPageversion:    require('./queryFunctions/getPageversion'),
    blog_newComment:        require('./queryFunctions/newComment'),
    blog_removePage:        require('./queryFunctions/removePage'),
    blog_setData:           require('./queryFunctions/setData'),
}
